<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Home extends CI_Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->load->model('article');
        $articles = $this->article->get();
        $view_data = array(
            'articles' => $articles,
        );
        $this->load->view('landing', $view_data);
    }

    public function register()
    {
        $this->load->view('register');
    }


}

/* End of file home.php */
/* Location: ./application/controllers/home.php */